# Generated by Django 5.1.5 on 2025-01-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ["id"],
                "verbose_name": "Cook",
                "verbose_name_plural": "Cooks",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["name"],
                "verbose_name": "Dish",
                "verbose_name_plural": "Dishes",
            },
        ),
    ]
