# Generated by Django 5.1.5 on 2025-01-24 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_cook_created_at_cook_updated_at_dish_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Years cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, message="Price cannot be less than zero."
                    )
                ],
            ),
        ),
    ]
